---
title: <p style="text-align:center; color:#00000040; font-family:'Phosphate'; font-size:275%">Workshops!</p>
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
```



```{r, fig.align='right', out.width=900}
library(wordcloud)

wds = c('R', 'Python', 'Statistics', 'Programming', 'Machine Learning', 'Stata', 'Bayesian',
        'Mixed Models', 'Text Analysis', 'Visualization', 'Web Scraping', 'Matlab', 'Regression', 
        'Spatial Analysis', 'Classification', 'Deep Learning', 'Factor Analysis', 'Reproducible Research', 
        'Image Processing', 'GIS',
        'SEM', 'Survival Analysis', 'Dimension Reduction', 'Stan', 'Networks', 'Survey Design')
set.seed(1234567)
# wordcloud(wds, 
#           freq = rev(seq_along(wds))/length(wds), 
#           scale = c(3,.25), 
#           rot.per = .3, 
#           color='#00000080',
#           font=1, 
#           family='Roboto Condensed')  #

wds = data.frame(wds, rev(seq_along(wds))/length(wds))
wordcloud2::wordcloud2(wds, 
                       size = .5,
                       # gridSize = .05,
                       rotateRatio = .75, 
                       color='#00000080',
                       ellipticity = 1,
                       shuffle = FALSE,
                       fontFamily='Stalemate',
                       shape='circle')  #
```

<br>
<br>
<p style="text-align:center; font-size:75%; font-family:'Futura'">Visit <span style="font-size:6">cscar.research.umich.edu/events</span> for times and offerings.</p>